version: "3"

services:
  caddy:
    image: caddy:2.6.4-alpine
    ports:
      - 8080:8080
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

  ui:
    build:
      context: ./ui
    volumes:
      - ./huiconsole.config.json:/var/www/html/huiconsole.config.json
  server:
    build:
      context: ./server
    depends_on:
      - mongo
    volumes:
      - ./run/logs:/app/logs/huiconsole-prod
      - ./huiconsole.config.json:/app/huiconsole.config.json

  mongo:
    image: mongo:6.0.3
    volumes:
      - ./run/mongo/db:/data/db