on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME_UI: ${{ github.repository }}-ui
  IMAGE_NAME_SERVER: ${{ github.repository}}-server

jobs:
  build-ui:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with: 
          username: ${{ secrets.DOCKERHUBACCOUNT }}
          password: ${{ secrets.DOCKERHUBPASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: docker.io/longjiahui/huiconsole-ui:latest
          context: ui
          
  build-server:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with: 
          username: ${{ secrets.DOCKERHUBACCOUNT }}
          password: ${{ secrets.DOCKERHUBPASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: docker.io/longjiahui/huiconsole-server:latest
          context: server
